// Every app and tray icon, generated from the two Flor de muerto masters (core/spec/icon) and the default theme's
// tokens (core/spec/tokens.json), through the one palette and renderer the desktop shell redraws with at runtime
// (core/app/rules/icon.js, issue 189). Nothing here is drawn by hand or holds a colour. --check fails on any output
// that is stale, and pnpm run build runs it.
//
//   desktop  build/icon.png and build/icon.ico (the packaged app), src/assets/tray (the tray before the page has said
//            which theme is in force: the macOS template and its Retina double, the Windows ICO, the Linux PNG)
//   About    core/app/assets/app-icon.png, which every shell bundles
//   iOS      the AppIcon set with its light, dark and tinted appearances. A theme cannot recolour the iOS icon at
//            runtime, so the store icon is the default theme's.
//   Android  the adaptive icon: the glyph as foreground at every density, the accent as background, and the glyph's
//            alpha as the monochrome layer launchers tint for themed icons
import sharp from 'sharp';
import pngToIco from 'png-to-ico';
import { writeFileSync, readFileSync, mkdirSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import { parseGlyph, iconPalette, iconColours, renderIcon, cssColour, toHex } from '../../core/app/rules/icon.js';

const at = (p) => new URL('../../' + p, import.meta.url);
const text = (p) => readFileSync(at(p), 'utf8');

export function masters() {
  return { full: parseGlyph(text('core/spec/icon/flor-de-muerto.svg')), small: parseGlyph(text('core/spec/icon/flor-de-muerto-small.svg')) };
}

// The default theme's palette for a scheme, from the tokens alone.
export function defaultPalette(scheme) {
  const colours = JSON.parse(text('core/spec/tokens.json')).color[scheme];
  return iconPalette(iconColours(colours, colours), scheme);
}

// The Android densities and the adaptive icon's 108 dp canvas at each.
export const ANDROID_DENSITIES = { mdpi: 1, hdpi: 1.5, xhdpi: 2, xxhdpi: 3, xxxhdpi: 4 };

const GENERATED = 'Generated by desktop/scripts/icons.mjs from core/spec/icon and core/spec/tokens.json; edit those, not this file.';

export async function icons(check = false) {
  const m = masters();
  const light = defaultPalette('light');
  const dark = defaultPalette('dark');
  const png = async (kind, size, palette = light, opts = {}) => {
    const img = renderIcon({ masters: m, palette, kind, size, ...opts });
    const raw = sharp(Buffer.from(img.data.buffer, img.data.byteOffset, img.data.length), { raw: { width: img.width, height: img.height, channels: 4 } });
    return (opts.opaque ? raw.removeAlpha() : raw).png({ compressionLevel: 9, adaptiveFiltering: false }).toBuffer();
  };
  const save = (name, bytes) => {
    const target = at(name);
    if (check) {
      let held = null;
      try { held = readFileSync(target); } catch { /* missing is stale */ }
      if (!held || !held.equals(bytes)) throw new Error('Stale generated icon: ' + name + ' (run pnpm --filter desktop icons)');
    } else {
      mkdirSync(new URL('.', target), { recursive: true });
      writeFileSync(target, bytes);
    }
  };
  const file = (name, body) => save(name, Buffer.from(body, 'utf8'));

  // Desktop: the packaged app's icon and the About page's.
  save('desktop/build/icon.png', await png('app', 1024));
  save('desktop/build/icon.ico', await pngToIco(await Promise.all([16, 24, 32, 48, 64, 128, 256].map((s) => png('app', s)))));
  save('core/app/assets/app-icon.png', await png('app', 256));
  // The tray before the page reports its theme (src/tray.js trayIcon); src/icon-images.js redraws it from then on.
  const tray = (name, bytes) => save('desktop/src/assets/tray/' + name, bytes);
  tray('trayTemplate.png', await png('template', 16));
  tray('trayTemplate@2x.png', await png('template', 32));
  tray('tray.png', await png('tray', 32));
  tray('tray.ico', await pngToIco(await Promise.all([16, 20, 24, 32, 40, 48].map((s) => png('tray', s)))));

  // iOS: light, dark and tinted, each a full square the system rounds.
  const naming = JSON.parse(text('core/spec/naming.json'));
  const set = 'ios/' + naming.product + '/Assets.xcassets/AppIcon.appiconset/';
  save(set + 'AppIcon.png', await png('ios', 1024, light, { opaque: true }));
  save(set + 'AppIcon-dark.png', await png('ios', 1024, dark, { opaque: true }));
  save(set + 'AppIcon-tinted.png', await png('tinted', 1024, light, { opaque: true }));
  const appearance = (value) => [{ appearance: 'luminosity', value }];
  file(set + 'Contents.json', JSON.stringify({
    images: [
      { filename: 'AppIcon.png', idiom: 'universal', platform: 'ios', size: '1024x1024' },
      { appearances: appearance('dark'), filename: 'AppIcon-dark.png', idiom: 'universal', platform: 'ios', size: '1024x1024' },
      { appearances: appearance('tinted'), filename: 'AppIcon-tinted.png', idiom: 'universal', platform: 'ios', size: '1024x1024' },
    ],
    info: { author: 'xcode', version: 1 },
  }, null, 2) + '\n');

  // Android: the adaptive icon's layers at every density, its background the accent, and the monochrome layer.
  const res = 'android/app/src/main/res/';
  for (const [density, scale] of Object.entries(ANDROID_DENSITIES)) {
    save(res + 'mipmap-' + density + '/ic_launcher_foreground.png', await png('foreground', 108 * scale));
    save(res + 'mipmap-' + density + '/ic_launcher_monochrome.png', await png('monochrome', 108 * scale));
  }
  file(res + 'mipmap-anydpi-v26/ic_launcher.xml', '<?xml version="1.0" encoding="utf-8"?>\n<!-- ' + GENERATED + ' -->\n<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n    <background android:drawable="@color/ic_launcher_background" />\n    <foreground android:drawable="@mipmap/ic_launcher_foreground" />\n    <monochrome android:drawable="@mipmap/ic_launcher_monochrome" />\n</adaptive-icon>\n');
  const accent = toHex(cssColour(JSON.parse(text('core/spec/tokens.json')).color.light.accent)).toUpperCase();
  file(res + 'values/colors.xml', '<?xml version="1.0" encoding="utf-8"?>\n<!-- ' + GENERATED + ' -->\n<resources>\n    <color name="ic_launcher_background">' + accent + '</color>\n</resources>\n');
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) await icons(process.argv.includes('--check'));
