import sharp from 'sharp';
import pngToIco from 'png-to-ico';
import { writeFileSync, readFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
// The app icons a person may choose in Settings (issue 167): one drawing, recoloured. core/spec/app-icons.json names
// each icon's tile and face; the default is the drawing exactly as it is.
const APP_ICONS = JSON.parse(readFileSync(new URL('../../core/spec/app-icons.json', import.meta.url), 'utf8'));
const NAMING = JSON.parse(readFileSync(new URL('../../core/spec/naming.json', import.meta.url), 'utf8'));
const longHex = (c) => (c.length === 4 ? '#' + [...c.slice(1)].map((x) => x + x).join('') : c).toLowerCase();

// The drawing in another icon's colours: the tile colour (the rect, the eyes and the smile) and the face (the bubble).
export function recolour(svg, icon) {
  const def = APP_ICONS.icons.find((i) => i.id === APP_ICONS.default);
  return svg.replace(/(fill|stroke)="(#[0-9a-f]{3,6})"/gi, (all, attr, colour) => {
    const c = longHex(colour);
    if (c === def.tile) return attr + '="' + icon.tile + '"';
    if (c === def.face) return attr + '="' + icon.face + '"';
    return all;
  });
}

// An iOS icon is a full square with no transparency, which iOS rounds itself: the tile fills the canvas.
const fullBleed = (svg) => svg.replace(/<rect\b[^>]*\/>/, (rect) => rect.replace(/\b(x|y)="[^"]*"/g, '$1="0"').replace(/\b(width|height)="[^"]*"/g, '$1="1024"').replace(/\s*rx="[^"]*"/, ''));

// The Android launcher foreground in another icon's face colour, and its adaptive icon over that icon's tile colour.
const androidForeground = (base, icon) => base.replace(/android:fillColor="#[0-9a-f]{6}"/gi, 'android:fillColor="' + icon.face.toUpperCase() + '"');
const androidAdaptive = (id) => '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by desktop/scripts/icons.mjs from core/spec/app-icons.json. -->\n<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n    <background android:drawable="@color/ic_launcher_background_' + id + '" />\n    <foreground android:drawable="@drawable/ic_launcher_foreground_' + id + '" />\n</adaptive-icon>\n';
const androidColours = (icons) => '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by desktop/scripts/icons.mjs from core/spec/app-icons.json: each chosen icon\'s launcher tile. -->\n<resources>\n'
  + icons.map((i) => '    <color name="ic_launcher_background_' + i.id + '">' + i.tile.toUpperCase() + '</color>\n').join('') + '</resources>\n';
const iosContents = JSON.stringify({ images: [{ filename: 'AppIcon.png', idiom: 'universal', platform: 'ios', size: '1024x1024' }], info: { author: 'xcode', version: 1 } }, null, 2) + '\n';
const pageMirror = (spec) => '// Generated from core/spec/app-icons.json by desktop/scripts/icons.mjs. Edit the spec, not this file.\nexport const APP_ICONS = ' + JSON.stringify(spec, null, 2) + ';\n';

export async function icons(check = false) {
  const input = new URL('../build/icon.svg', import.meta.url);
  const png = await sharp(fileURLToPath(input)).resize(1024, 1024).png().toBuffer();
  const save = (name, bytes) => { const target = new URL('../build/' + name, import.meta.url); if (check) { if (!readFileSync(target).equals(bytes)) throw new Error('Stale generated icon: ' + name); } else { mkdirSync(new URL('.', target), { recursive: true }); writeFileSync(target, bytes); } };
  save('icon.png', png);
  const sizes = await Promise.all([16, 32, 48, 256].map((size) => sharp(png).resize(size, size).png().toBuffer()));
  save('icon.ico', await pngToIco(sizes));
  // The icon the About page draws at its top on every platform (issue 171). It lives in core/app, which every shell
  // bundles, so the iPhone, the Android app and the desktop all show this one drawing; 256 pixels covers the token's
  // size (size.app-icon) at three device pixels per point.
  save('../../core/app/assets/app-icon.png', await sharp(png).resize(256, 256).png().toBuffer());
  // The tray's icons (src/tray.js trayIcon). macOS draws a template image: a black silhouette with its face cut out,
  // which the menu bar redraws light or dark to suit itself, at 16 points and twice that for Retina. Windows and Linux
  // show the app's own colours: an ICO with every size the notification area asks for at each display scaling, and a
  // PNG for the panel. They live under src/ so the packaged app carries them.
  const template = fileURLToPath(new URL('../build/tray-template.svg', import.meta.url));
  const tray = (name, bytes) => save('../src/assets/tray/' + name, bytes);
  tray('trayTemplate.png', await sharp(template).resize(16, 16).png().toBuffer());
  tray('trayTemplate@2x.png', await sharp(template).resize(32, 32).png().toBuffer());
  tray('tray.png', await sharp(png).resize(32, 32).png().toBuffer());
  const traySizes = await Promise.all([16, 20, 24, 32, 40, 48].map((size) => sharp(png).resize(size, size).png().toBuffer()));
  tray('tray.ico', await pngToIco(traySizes));
  // Every icon Settings offers (issue 167): the picture the page shows in the choice and the desktop sets on its window
  // and Dock, and, for every icon but the default (which is already each platform's primary icon), an iOS alternate
  // icon set and an Android adaptive icon with its launcher colour. The page reads the generated mirror of the spec.
  const svg = readFileSync(input, 'utf8');
  const ios = '../../ios/' + NAMING.product + '/Assets.xcassets/';
  const res = '../../android/app/src/main/res/';
  const foreground = readFileSync(new URL(res + 'drawable/ic_launcher_foreground.xml', new URL('../build/', import.meta.url)), 'utf8');
  for (const icon of APP_ICONS.icons) {
    const drawn = await sharp(Buffer.from(recolour(svg, icon), 'utf8')).resize(1024, 1024).png().toBuffer();
    save('../../core/app/assets/app-icons/' + icon.id + '.png', await sharp(drawn).resize(256, 256).png().toBuffer());
    if (icon.id === APP_ICONS.default) continue;
    const square = await sharp(Buffer.from(fullBleed(recolour(svg, icon)), 'utf8')).resize(1024, 1024).flatten({ background: icon.tile }).removeAlpha().png().toBuffer();
    save(ios + 'AppIcon-' + icon.id + '.appiconset/AppIcon.png', square);
    save(ios + 'AppIcon-' + icon.id + '.appiconset/Contents.json', Buffer.from(iosContents, 'utf8'));
    save(res + 'drawable/ic_launcher_foreground_' + icon.id + '.xml', Buffer.from(androidForeground(foreground, icon), 'utf8'));
    save(res + 'mipmap-anydpi-v26/ic_launcher_' + icon.id + '.xml', Buffer.from(androidAdaptive(icon.id), 'utf8'));
  }
  save(res + 'values/app_icons.xml', Buffer.from(androidColours(APP_ICONS.icons.filter((i) => i.id !== APP_ICONS.default)), 'utf8'));
  save('../../core/app/rules/app-icons-spec.js', Buffer.from(pageMirror(APP_ICONS), 'utf8'));
}
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) await icons(process.argv.includes('--check'));
