import Foundation
import UIKit
import UserNotifications
import WebKit

/// The shell's half of core/spec/host-bridge.json.
///
/// Every command a page may call lives in that spec and the shell refuses
/// anything else, so a platform difference is data in the spec rather than a
/// branch in core. The page reaches this through window.bridge.call, which the
/// injected script below installs; a reply is a call back into the page, so the
/// protocol is one message in and one JavaScript call out.
/// The app icon chosen in Settings (issue 167). Every icon core/spec/app-icons.json names but the default ships as an
/// alternate icon set, AppIcon-<id>, generated by the shared icon pipeline (desktop/scripts/icons.mjs) and listed in
/// project.yml; a choice with no colours of its own (Follow theme) is the primary icon, drawn in the default theme,
/// because iOS cannot recolour an installed icon (issues 189, 246). iOS confirms every change with an alert of its own, so the page asks
/// only when the choice changes, and this asks iOS only when the icon on show differs.
enum AppIcons {
    enum Target: Equatable { case primary, alternate(String), refused }

    /// defaultID is the choice in force when none is stored; fixed is every choice that carries its own colours (so it
    /// has a set to be shown from), which is every choice but Follow theme.
    struct Spec { let defaultID: String; let ids: [String]; let fixed: Set<String> }

    static var spec: Spec? {
        guard let data = try? BundledSpec.data(at: "spec/app-icons.json"),
              let object = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let defaultID = object["default"] as? String,
              let families = object["families"] as? [[String: Any]] else { return nil }
        var ids: [String] = []
        var fixed = Set<String>()
        for family in families {
            guard let variants = family["variants"] as? [String: Any] else { continue }
            for key in ["light", "dark"] {
                guard let variant = variants[key] as? [String: Any], let id = variant["id"] as? String else { continue }
                ids.append(id)
                if variant["colors"] != nil { fixed.insert(id) }
            }
        }
        if let follow = object["followTheme"] as? [String: Any], let id = follow["id"] as? String { ids.append(id) }
        return Spec(defaultID: defaultID, ids: ids, fixed: fixed)
    }

    /// The alternate icon sets the built app carries, as the asset catalog compiler wrote them into the Info.plist.
    static func alternates(in bundle: Bundle = .main) -> Set<String> {
        guard let icons = bundle.object(forInfoDictionaryKey: "CFBundleIcons") as? [String: Any],
              let alternates = icons["CFBundleAlternateIcons"] as? [String: Any] else { return [] }
        return Set(alternates.keys)
    }

    /// What an id asks iOS for: its own alternate set for a fixed choice the app carries, the primary icon for a
    /// choice with no colours of its own (Follow theme, which iOS cannot recolour, so the store icon stands in) and for
    /// a default the build carries no set for, and nothing for an id the spec does not name or the build does not carry.
    static func target(for icon: String, spec: Spec, alternates: Set<String>) -> Target {
        guard spec.ids.contains(icon) else { return .refused }
        if !spec.fixed.contains(icon) { return .primary }
        let name = "AppIcon-" + icon
        if alternates.contains(name) { return .alternate(name) }
        return icon == spec.defaultID ? .primary : .refused
    }

    /// The live icon behaviour, behind one value so a test can hold the choice to asking iOS for the set without a real
    /// change: iOS answers an icon change with an alert of its own that a unit test cannot dismiss, so the device proves
    /// the change and AppIconTests proves the bridge asks for the right set and reports what it settled on.
    struct Runtime {
        var supportsAlternateIcons: () -> Bool
        var alternateIconName: () -> String?
        var setAlternateIconName: (String?, @escaping (Error?) -> Void) -> Void

        static let live = Runtime(
            supportsAlternateIcons: { UIApplication.shared.supportsAlternateIcons },
            alternateIconName: { UIApplication.shared.alternateIconName },
            setAlternateIconName: { name, completion in
                UIApplication.shared.setAlternateIconName(name, completionHandler: completion)
            }
        )
    }

    static func apply(_ icon: String, runtime: Runtime = .live, done: @escaping ([String: Any]) -> Void) {
        guard let spec = spec, runtime.supportsAlternateIcons() else { done(["applied": false, "icon": icon]); return }
        let name: String?
        switch target(for: icon, spec: spec, alternates: alternates()) {
        case .refused: done(["applied": false, "icon": icon]); return
        case .primary: name = nil
        case .alternate(let alternate): name = alternate
        }
        if runtime.alternateIconName() == name { done(["applied": true, "icon": icon]); return }
        runtime.setAlternateIconName(name) { error in
            DispatchQueue.main.async {
                var answer: [String: Any] = ["applied": error == nil, "icon": icon]
                if let error { answer["detail"] = error.localizedDescription }
                done(answer)
            }
        }
    }
}

final class HostBridge: NSObject, WKScriptMessageHandler {
    /// The name the injected script posts under.
    static let messageName = "cuateBridge"

    /// The hook the shell calls to settle a pending call.
    static let resolveHook = "__cuateResolve"

    /// Storage keys are lower-case words joined by dots, the same shape the
    /// desktop enforces, so a key is a name and not an arbitrary string.
    private static let keyPattern = "^[a-z][a-z0-9.]{0,63}$"

    weak var webView: WKWebView?

    /// Keeps the web view on the system's scheme while the window shows the page's; registered on the first call.
    private var systemObserver: UITraitChangeRegistration?

    private let store: KeychainSecureStore
    private let commands: Set<String>

    init(store: KeychainSecureStore, commands: Set<String>) {
        self.store = store
        self.commands = commands
    }

    /// The command names the bundled spec declares.
    static func commandNames() -> Set<String> {
        guard let data = try? BundledSpec.data(at: "spec/host-bridge.json"),
              let object = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let commands = object["commands"] as? [String: Any] else {
            return []
        }
        return Set(commands.keys)
    }

    /// The document-start script that installs window.bridge over the message
    /// handler. Installed before the page boots, because the page calls
    /// window.bridge during its own first render.
    static var injectedScript: String {
        var script = "(function () {\n"
        script += "  if (window.bridge) { return; }\n"
        script += "  window.__cuatePending = {};\n"
        script += "  window.__cuateSeq = 0;\n"
        script += "  window.\(resolveHook) = function (payload) {\n"
        script += "    var pending = window.__cuatePending[payload.id];\n"
        script += "    if (!pending) { return; }\n"
        script += "    delete window.__cuatePending[payload.id];\n"
        script += "    if (payload.ok) { pending.resolve(payload.value); }\n"
        script += "    else { pending.reject(new Error(String(payload.value))); }\n"
        script += "  };\n"
        script += "  window.bridge = {\n"
        script += "    call: function (name, args) {\n"
        script += "      return new Promise(function (resolve, reject) {\n"
        script += "        var id = String(++window.__cuateSeq);\n"
        script += "        window.__cuatePending[id] = { resolve: resolve, reject: reject };\n"
        script += "        window.webkit.messageHandlers.\(messageName).postMessage({ id: id, name: name, args: args || {} });\n"
        script += "      });\n"
        script += "    }\n"
        script += "  };\n"
        script += "})();\n"
        return script
    }

    func userContentController(_ controller: WKUserContentController, didReceive message: WKScriptMessage) {
        guard message.name == Self.messageName,
              let body = message.body as? [String: Any],
              let id = body["id"] as? String,
              let name = body["name"] as? String else { return }
        let args = body["args"] as? [String: Any] ?? [:]
        dispatch(id: id, name: name, args: args)
    }

    private func dispatch(id: String, name: String, args: [String: Any]) {
        guard commands.contains(name) else {
            settle(id: id, ok: false, value: "undeclared bridge command: " + name)
            return
        }
        switch name {
        case "storage.get":
            settle(id: id, ok: true, value: storageGet(args))
        case "storage.set":
            settle(id: id, ok: true, value: storageSet(args))
        case "storage.delete":
            settle(id: id, ok: true, value: storageDelete(args))
        case "app.info":
            settle(id: id, ok: true, value: appInfo())
        case "app.icon":
            // The app icon chosen in Settings (issue 167), as one of the alternate icon sets the asset catalog ships.
            AppIcons.apply(args["icon"] as? String ?? "") { [weak self] answer in
                self?.settle(id: id, ok: true, value: answer)
            }
        case "notify":
            settle(id: id, ok: true, value: notify(args))
        case "open.external":
            settle(id: id, ok: true, value: openExternal(args))
        case "file.save":
            // A document pressed in a conversation (issue 219) is offered for saving under its real name through the
            // system's share sheet, which includes Save to Files.
            settle(id: id, ok: true, value: saveFile(args))
        case "updates.check":
            // The page runs this phone's check itself from the release feed (issue 192), so the shell has no state of
            // its own to answer; the one bridge spec still declares the command for the desktop's tray check.
            settle(id: id, ok: true, value: NSNull())
        case "updates.releases":
            // The repository's public release feed, read here because the page loads nothing from the network; the
            // page decides from it with the rule both phones share (core/app/rules/updates.js).
            releases(id: id)
        case "updates.configure":
            // iOS cannot download or install an update itself, so there is nothing to configure or download.
            settle(id: id, ok: true, value: false)
        case "updates.download":
            settle(id: id, ok: true, value: false)
        case "updates.install":
            // A newer build is installed in TestFlight, so installing it is opening TestFlight.
            Task { @MainActor [weak self] in
                let opened = await TestFlight.open()
                self?.settle(id: id, ok: true, value: opened != nil)
            }
        // A phone has no window to minimise, maximise or close, so the window commands answer false and the bar is
        // never drawn; the one bridge spec still declares them for the desktop.
        case "window.minimize":
            settle(id: id, ok: true, value: false)
        case "window.toggleMaximize":
            settle(id: id, ok: true, value: false)
        case "window.close":
            settle(id: id, ok: true, value: false)
        // The status bar draws over the page's colours, so its icons follow the page's scheme rather than the system's.
        case "window.appearance":
            settle(id: id, ok: true, value: appearance(args))
        // The app icon follows the theme on the desktop (issue 189). iOS cannot recolour its icon at runtime, so its
        // icon is the default theme's light, dark and tinted set, and the system draws the unread badge; this answers
        // false.
        case "icon.redraw":
            settle(id: id, ok: true, value: false)
        default:
            settle(id: id, ok: false, value: "undeclared bridge command: " + name)
        }
    }

    /// Dark icons on a light page and light icons on a dark one, over the page's own fill, so the clock and the battery
    /// stay readable in either scheme. The page's choice wins over the system's, since it may differ.
    ///
    /// The status bar takes its style from the window, but the page reads the system's scheme from its web view, and a
    /// page that follows the system must keep seeing the system's. So the window takes the page's scheme and the web
    /// view keeps the scene's own, which a window's override never reaches, updated whenever the system's changes.
    private func appearance(_ args: [String: Any]) -> Bool {
        guard let webView, let window = webView.window, let scene = window.windowScene else { return false }
        let dark = (args["scheme"] as? String) == "dark"
        window.overrideUserInterfaceStyle = dark ? .dark : .light
        webView.overrideUserInterfaceStyle = scene.traitCollection.userInterfaceStyle
        if systemObserver == nil {
            systemObserver = scene.registerForTraitChanges([UITraitUserInterfaceStyle.self]) { [weak self] (scene: UIWindowScene, _: UITraitCollection) in
                self?.webView?.overrideUserInterfaceStyle = scene.traitCollection.userInterfaceStyle
            }
        }
        if let fill = Self.color(args["background"] as? String) {
            webView.backgroundColor = fill
            webView.scrollView.backgroundColor = fill
            webView.underPageBackgroundColor = fill
        }
        return true
    }

    /// A #rrggbb colour, the form the tokens write; anything else leaves the fill as it was.
    static func color(_ text: String?) -> UIColor? {
        guard let text, text.count == 7, text.hasPrefix("#"), let value = UInt32(text.dropFirst(), radix: 16) else { return nil }
        return UIColor(red: CGFloat((value >> 16) & 0xff) / 255, green: CGFloat((value >> 8) & 0xff) / 255,
                       blue: CGFloat(value & 0xff) / 255, alpha: 1)
    }

    private func storageGet(_ args: [String: Any]) -> Any {
        guard let key = validKey(args) else { return NSNull() }
        return store.get(key) ?? NSNull()
    }

    private func storageSet(_ args: [String: Any]) -> Bool {
        guard let key = validKey(args), let value = args["value"] as? String, value.utf8.count <= 8192 else { return false }
        return store.set(key, value)
    }

    private func storageDelete(_ args: [String: Any]) -> Bool {
        guard let key = validKey(args) else { return false }
        return store.delete(key)
    }

    private func validKey(_ args: [String: Any]) -> String? {
        guard let key = args["key"] as? String else { return nil }
        return key.range(of: Self.keyPattern, options: .regularExpression) != nil ? key : nil
    }

    /// The client's half of the About page's build report: the full version, the channel it follows and the build
    /// number TestFlight lists it under, all from the bundle (issue 192).
    private func appInfo() -> [String: Any] {
        let version = Naming.buildVersion
        let build = BuildIdentity.build
        return [
            "product": Naming.product,
            "version": version,
            "channel": BuildIdentity.channel(of: version),
            "build": build.isEmpty ? NSNull() : build,
            "updateChannel": BuildIdentity.channel(of: version) == "dev" ? "dev" : "latest",
            "platform": "ios",
        ]
    }

    private func releases(id: String) {
        Task { @MainActor [weak self] in
            do {
                let feed = try await Self.feed()
                self?.settle(id: id, ok: true, value: feed)
            } catch {
                self?.settle(id: id, ok: false, value: "the release list could not be read: " + error.localizedDescription)
            }
        }
    }

    /// The feed, or, in a Debug build launched with --update-fixture, the synthetic one a UI test reads, copied into
    /// test builds only (project.yml), so the capture of a newer build never depends on the network.
    private static func feed() async throws -> String {
        #if DEBUG
        if ProcessInfo.processInfo.arguments.contains("--update-fixture"),
           let url = Bundle.main.url(forResource: "release-feed-fixture", withExtension: "atom") {
            return try String(contentsOf: url, encoding: .utf8)
        }
        #endif
        return try await Releases.readFeed()
    }

    private func notify(_ args: [String: Any]) -> Bool {
        let title = String((args["title"] as? String ?? "").prefix(200))
        let body = String((args["body"] as? String ?? "").prefix(500))
        guard !title.isEmpty else { return false }
        let content = UNMutableNotificationContent()
        content.title = title
        content.body = body
        // Authorization is asked for on the first notification rather than at
        // launch, so a fresh install is not greeted by a permission dialog
        // before it has drawn anything.
        let center = UNUserNotificationCenter.current()
        center.requestAuthorization(options: [.alert, .sound]) { _, _ in }
        let request = UNNotificationRequest(identifier: UUID().uuidString, content: content, trigger: nil)
        center.add(request)
        return true
    }

    /// A document pressed in a conversation (issue 219): the page hands the bytes as base64 under the file's real
    /// name, and the system's share sheet, which includes Save to Files, is offered from the top view controller.
    private func saveFile(_ args: [String: Any]) -> Bool {
        guard let name = args["name"] as? String, !name.isEmpty,
              let data = args["data"] as? String, let bytes = Data(base64Encoded: data) else { return false }
        let safe = (name as NSString).lastPathComponent
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(safe.isEmpty ? "Attachment" : safe)
        do { try bytes.write(to: url, options: .atomic) } catch { return false }
        DispatchQueue.main.async { [weak self] in
            guard let host = self?.webView?.window?.rootViewController else { return }
            let sheet = UIActivityViewController(activityItems: [url], applicationActivities: nil)
            if let pop = sheet.popoverPresentationController {
                pop.sourceView = host.view
                pop.sourceRect = CGRect(x: host.view.bounds.midX, y: host.view.bounds.midY, width: 1, height: 1)
            }
            host.present(sheet, animated: true)
        }
        return true
    }

    private func openExternal(_ args: [String: Any]) -> Bool {
        guard let text = args["url"] as? String, let url = URL(string: text),
              let scheme = url.scheme?.lowercased(), scheme == "http" || scheme == "https" else {
            return false
        }
        DispatchQueue.main.async {
            UIApplication.shared.open(url)
        }
        return true
    }

    /// Settle the page's pending call. The whole payload is one JSON object, so
    /// a value that is nil, a string, a bool or a dictionary travels the same
    /// way and the page's resolver has one shape to read.
    private func settle(id: String, ok: Bool, value: Any) {
        let payload: [String: Any] = ["id": id, "ok": ok, "value": value]
        guard JSONSerialization.isValidJSONObject(payload),
              let data = try? JSONSerialization.data(withJSONObject: payload),
              let json = String(data: data, encoding: .utf8) else { return }
        webView?.evaluateJavaScript("window.\(Self.resolveHook) && window.\(Self.resolveHook)(\(json));")
    }
}
